# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/blossom/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/blossom


PRODUCT_PACKAGES += \
    libfmjni
